---
title: "Reflecting on my time as an Enrichment student at the Alan Turing Institute."
---

- **The best part was the people**

The application for the enrichment scheme was one of the most unique applications I’d ever done. I did not have to pitch a project, or showcase my CV and achievements in academia at all; I had to showcase how being part of the Alan Turing Institute would bring benefits both to me and them, hence how it would be an “enriching experience”. I am not sure if because of this more unique way of application/selection, or simply due to chance, but the enrichment cohort that was selected for 2022/2023 was full of refreshing individuals. Good listeners, funny and intelligent. Going to the office was fun. Knowing I'd see people who were happy, ready to laugh, be silly, and work hard, was like a warm and cosy container in the busy city of London.
We were all doing different PhD projects, from environment to microbiology, to physics, cancer research, neuroscience and more. It was very refreshing to interact with other PhD students who were not doing the same research I was, but we could still relate on the hardships and successes of each other. Undoubtedly, the best part of my enrichment experience was the people I met. 

- **My confidence in doing research had a big boost**

As someone who was not trained in Computer Science, I was never taught how to version control, or program neatly and aim for reproducibility and accessibility as part of my research. During my career, I have often times felt like an impostor – pretending I know how to code but not really sure what I was doing. At the Alan Turing Institute, I was able to work with a varied community that made me feel welcome and comnfortable to learn about data science, reproducibility, ethics and combine them all together in a way that felt smooth. 
Although the Institute has a focus on data science and artificial intelligence, my experience was that there were people from all sorts of backgrounds, and not necessarily trained in computer sciences either. I spoke with people who had done grassroots work prior to joining, people who studied philosophy, economy, biology; it was a great environment to learn from different people. I think this really helps the Turing community to be respectful and open minded, understanding people come from different walks in life and have different and complimentary skills. It was thanks to all the interactions I had with the different teams like The Turing Way community, Turing Commons, Research and Engineering team, TPS team, that I was able to hone in on my programming skills and develop efficient pipelines and workflows in my PhD research. Likewise, seeing the variety of ways in which people worked, gave me confidence in knowing that I am doing alright, and that I am capable of learning and implementing well-planned work. 

- **Ethics was a big topic for me during my time here**

My research is interdisciplinary; it's a mix between neuroscience, computer science and ethics. I create computer models of specific molecules that are important for understanding how memory works. I also look at potential bias in my research, implementing a [Data Hazards framework](https://datahazards.com/contents/data-hazards.html). As part of my enrichment experience, I was able to co-organise (with Ceilidh Welsh, another Enrichment student) a hybrid, one-day symposium on [Data Hazards, Ethics and Reproducibility](https://www.eventbrite.com/e/online-data-hazards-ethics-and-reproducibility-one-day-symposium-tickets-517490858087). This was thanks to a Grassroots Student training fund that the Institute has made available for students to organise training and skills development activities. I also participated in multiple collaboration cafes that the Turing Way hosts and attended training such as ["Turing Commons: AI Ethics and Governance"](https://www.eventsforce.net/turingevents/frontend/reg/thome.csp?pageID=81509&eventID=232&traceRedir=2). Being part of these events has been crucial for my PhD, as it enabled me to have conversations about bias, ethics and reproducibility with people who were knowledgeable in these fields. 

I would encourage any PhD student, especially those of marginalised backgrounds to look into this scheme. The Turing is doing hard work on including people who have historically been disadvantaged by the oppressive society we live in, people like first generation academics, females and gender-non conforming, lgbtq+ identifying, people of colour and more. If you are looking to build community, work with different teams and quite literally "enrich" your PhD with others who take EDI seriously, maybe consider this opportunity.